name: flutter_persistent_queue
description: >
  Simple file-based non-volatile persistent queue implementation for flutter.
  Ideal for in-device sequential buffers that must persist between app runs.
version: 6.2.0
homepage: https://github.com/oakromulo/flutter_persistent_queue
repository: https://github.com/oakromulo/flutter_persistent_queue.git
issue_tracker: https://github.com/oakromulo/flutter_persistent_queue/issues

environment:
  flutter: ">=1.12.13+hotfix.5"
  sdk: ">=2.7.0"

dependencies:
  flutter:
    sdk: flutter
  localstorage: ^4.0.0+1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
